export const INVALID_VERSION_NAME =
  'Invalid version name (must be semver-valid)'
export const MAJOR_LABELS = 'major-labels'
export const MINOR_LABELS = 'minor-labels'
export const PATCH_LABELS = 'patch-labels'
export const CHANNEL = 'channel'
export const NEW_BUILD_FOR_PRERELEASE = 'new-build-for-prerelease'
export const DEFAULT_INITIAL_VERSION = 'default-initial-version'
export const NO_MERGED_PRS = 'No merged pull requests found since latest tag'
export const NO_MATCHING_LABELS =
  'No pull requests with matching labels found since latest tag'
export const UNKNOWN = 'unknown'
export const NONE = 'none'
export const MAJOR = 'major'
export const MINOR = 'minor'
export const PATCH = 'patch'
export const PRERELEASE = 'prerelease'
export const STABLE = 'stable'
export const V = 'v'
export const NO_CHANGES_FOUND = 'No changes found'
export const NEXT_VERSION = 'next-version'
